### ISSUE TITLE
jessie does not disconnect  /dev/nbd0

### ISSUE THREAD

**Issue by coolya** [scaleway/image-debian#10]
I have build the jessie by hand. If I issue a reboot command the server reboots but hangs when it tries to access  /dev/nbd0 .
Tested it with multiple servers / images and it was always reproduceable.

**Comment by aimxhaisse** [comment]
Are you using `systemctl reboot`?

**Comment by coolya** [comment]
Did not make any difference for me if I use `systemctl reboot` or simply `reboot`

**Comment by moul** [comment]
We will release the new initrd soon, for now the Jessie image is not public because of this

**Comment by aimxhaisse** [comment]
Yes! That's because of the initrd. I tested to reboot this image on 32 servers and it was fine on all of them.

**Comment by moul** [comment]
We just need to validate the new initrd everywhere before making it public

**Comment by moul** [comment]
The new jessie image is now OK
