### ISSUE TITLE
Handle serial logout

### ISSUE THREAD

**Issue by aimxhaisse** [scaleway/image-debian#12]
How to reproduce:

- add a password (passwd)
- login via the CLI (scw attach)
- logout

The login prompt does not appear anymore.

**Comment by aimxhaisse** [comment]
Restored service ttyS0.

Note: this service hangs when used with a 3.2 LSP kernel.

**Comment by moul** [comment]
Can you add a warning service that checks for the kernel version and print a big warning ?

**Comment by aimxhaisse** [comment]
yes
