### ISSUE TITLE
Jessie: empty /etc/machine-id after install

### ISSUE THREAD

**Issue by markshep** [scaleway/image-debian#24]
After installing a Debian Jessie image I noticed that the systemd-journald service had failed and couldn't be started. After searching around I found that the solution was to run "systemd-machine-id-setup" which generated a machine ID and saved it to /etc/machine-id. The service could then be started.

Please could you make the installation process run that command so that in the future newly created Debian Jessie servers don't have this problem?

**Comment by aimxhaisse** [comment]
On systemd images, we run the following script at startup for that purpose:

https://github.com/scaleway/image-tools/blob/master/skeleton-common/usr/local/sbin/oc-gen-machine-id

I thought it was fixed on Jessie, could you provide the ID of the image you are using?

**Comment by aimxhaisse** [comment]
root@clever-meitner:~# uuidgen
    bash: uuidgen: command not found

**Comment by markshep** [comment]
The format of `/etc/machine-id` after running `systemd-machine-id-setup` differs from the output of `uuidgen` in that the former contains no hyphens.  But maybe that's not a problem, as long as `/etc/machine-id` contains something unique?
