### ISSUE TITLE
Upgrade of Debian 8.1 makes the system unbootable

### ISSUE THREAD

**Issue by MarcusCarlson** [scaleway/image-debian#28]
From freshly installed Debian 8.1 system (as of 5th of September) I did an upgrade (apt-get update && apt-get upgrade) and after a reboot of the server (both doing #reboot and Turn off using the Web UI) the server doesn't come back. This was tried twice so not a one time thing.

The packages updated was:
root@mejlamej-arm:~# apt-get upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
apt base-files cron dbus libapt-inst1.5 libapt-pkg4.12 libc-bin libc6
libdbus-1-3 libdns-export100 libgnutls-deb0-28 libgnutls-openssl27
libirs-export91 libisc-export95 libisccfg-export90 libnss3 libsystemd0
libudev1 locales multiarch-support python-apt python-apt-common rsyslog
screen systemd systemd-sysv tcpdump tzdata udev
29 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 19.3 MB of archives.
After this operation, 1000 kB disk space will be freed.
Do you want to continue? [Y/n]

The console gives this error:

>>> Failed to switch_root, does /newroot//sbin/init exists ?
>>> Rescue Shell (Busybox's /bin/sh)
>>> To continue, press 'control-D'
>>> To reboot, go to https://cloud.scaleway.com/

BusyBox v1.22.1 (Debian 1:1.22.0-9+deb8u1) built-in shell (ash)
Enter 'help' for a list of built-in commands.

/bin/sh: can't access tty; job control turned off
/ #

As the update involved systemd my suspicion is that your image includes something special handling of init that the upgrade of systemd restores to default.

For the info, /newroot/sbin/init does exists

/ # ls /newroot/sbin/ -la | grep init
lrwxrwxrwx 1 root 0 20 Aug 31 01:06 init -> /lib/systemd/systemd
lrwxrwxrwx 1 root 0 14 Aug 31 01:06 telinit -> /bin/systemctl

also /lib/systemd/systemd exists (but in /newroot of course)

Doing the following after an upgrade seems to "fix" the issue:

cd /sbin/ && rm init && ln ../lib/systemd/systemd init -s

However, a more elegant and future proof solution would be great.

Best regards,
Marcus

**Comment by moul** [comment]
I think systemd' upgrade replaced the relative symlink to an absolute one, it blocks the check we are doing in our initrd, for now you did the good fix

**Comment by MarcusCarlson** [comment]
Thanks for really good support!

**Comment by moul** [comment]
You're welcome

**Comment by falzm** [comment]
I just got bitten by a similar issue after dist-upgrading and rebooting my server. Here is what I get in the web console:

```
(normal booting sequence)
...
cp: recursion detected, omitting directory '/initramfs'
Begin: Checking user input for debug mode ...  done.
Begin: Checking user input for debug shell ...  done.
Begin: Signaling the server is kernel-started to the control plane ... Failure: unable to signal server is kernel-started. done. 
Begin: Signaling the server is kernel-started to the control plane ... Success: control plane is aware that server is kernel-started. done. 
Begin: Adjusting time (ntp) ...  done. 
Begin: Attaching nbd0 ... EXT3-fs (nbd0): error: couldn't mount because of unsupported optional features (240) 
 done. 
Begin: Mounting nbd0 root ... EXT2-fs (nbd0): error: couldn't mount because of unsupported optional features (244) 
EXT4-fs (nbd0): recovery complete 
EXT4-fs (nbd0): mounted filesystem with ordered data mode. Opts: (null) 
 done. 
Begin: Checking metadata in case we skip to wait for secondary volumes to be ready ...  done.                                                                                
Begin: Attaching nbd0 ...  done.                                                  
Begin: Signaling the server is booted to the control plane ... Success: control plane is aware that server is booted. done. 
Begin: Checking metadata for debug shell ... done. 
Failed to switch_root, dropping to a shell 

BusyBox v1.22.1 (Ubuntu 1:1.22.0-9ubuntu1) built-in shell (ash) 
Enter 'help' for a list of built-in commands.
```

I don't see how can your workaround can help in this situation... Help :/

**Comment by moul** [comment]
Hi @falzm, this is fixed in the latest initrd, you can use the latest initrd by using a more recent bootscript

I suggest you to take the `4.1.6-std` one

**Comment by falzm** [comment]
Hi @moul 

But how can I fix my server's OS without reinstalling it? Each time I boot it the init sequence fails.

**Comment by moul** [comment]
By switching to the new bootscript, you will have the new initrd which should lets you but on a dist-upgraded system

Can you just give a try ?

Else, you will at least have a debug shell in the initrd with your system mounted in `/newroot`, so you can find what make the boot impossible and manually fix it, but I think you will only have to change the booscript to fix your issue without any other manual intervention

**Comment by moul** [comment]
For your information, we released upgraded versions of Debian images, so now the Jessie one is a `8.2`, and we also added a `Sid` version if you feel like Indiana Jones :) (just in case you consider to drop your old server and boot a new one)

**Comment by falzm** [comment]
OK, I confirm that booting the server now works. Does rebooting fetch a new initrd?

**Comment by moul** [comment]
Rebooting fetches again the `initrd` associated with your `bootscript`

Except for hot-fix, we won't change an `initrd` from a boot to another, but if you switch from a `bootscript` to another manually, then your kernel and `initrd` will change
