### ISSUE TITLE
Suggest adding kmod package to Debian 8.1 image

### ISSUE THREAD

**Issue by MarcusCarlson** [scaleway/image-debian#29]
I would suggest adding the package "kmod" to the Debian 8.1 image to have the system not being reported as "degraded" by systemd as the kmod-static-nodes.service cannot be started because of missing command /bin/kmod

**Comment by moul** [comment]
kmod won't work as expected on scaleway, so I suggest to disable this service to avoid the warning

@aimxhaisse what do you think ?
