### ISSUE TITLE
Debian wheezy unable to reboot

### ISSUE THREAD

**Issue by valentinul** [scaleway/image-debian#36]
Hi,
I've just deployed a server with debian wheezy and it seems that when I do a reboot it is unable to do a clean reboot. I've attached a screenshot with the actual errors.
![screen shot 2015-09-14 at 13 31 12](https://cloud.githubusercontent.com/assets/5860438/9848883/90758f02-5ae5-11e5-9008-e2a3abf7b843.png)

**Comment by moul** [comment]
I found the issue, I'm patching it now

**Comment by valentinul** [comment]
Perfect, let me know when I spin up another server.

**Comment by moul** [comment]
Fixed with: https://github.com/scaleway/image-tools/commit/7e617008c00ad92ec57f705118f92bd203ac0899

**Comment by moul** [comment]
The new image is available here: https://cloud.scaleway.com/#/servers/new?image=013a046a-b109-4e42-8370-15cde6365f2b

**Comment by moul** [comment]
You can try to hotfix an existing image by applying same changes : https://github.com/scaleway/image-tools/commit/88ecd4b00b0f3460ebb506f684fd324095445535

**Comment by valentinul** [comment]
Hi,

It seems that after you made an update to the image the serial console is not working anymore. This applies also for the jessie image. I've opened a ticket regarding this also..
