### ISSUE TITLE
Debian wheezy unable to reboot

### ISSUE THREAD

**Issue by valentinul** [scaleway/image-debian#38]
Hi Manfred,
I had to open the issue again...The problem is still there. I've attached the screenshot. 
![screen shot 2015-09-15 at 15 11 07](https://cloud.githubusercontent.com/assets/5860438/9877451/31ac45a0-5bbd-11e5-8295-ec7f0e68adfd.png)

**Comment by moul** [comment]
Ok, so I though my changes were enough, but I think we still miss a script that prevent `init` to kill the main `qemu-nbd0` process, it will need a little more work

For now I can suggest to switch to another images, every other images are rebooting find, **debian jessie** included

**Comment by moul** [comment]
Calling this:

```bash
ps x | grep xnbd-client | grep -v grep | awk '{print $1}' > /run/sendsigs.omit.d/nbd
```

Seems to works, you can maybe add this in your /etc/rc.local script

I'm trying to fixit from within the initrd (see https://github.com/scaleway/initrd/pull/88), if so, the issue should be fixed without rebuilding the image

**Comment by valentinul** [comment]
Unfortunately the reboot still fails in the same way.

**Comment by moul** [comment]
Yep, actually this is not the same bug, the hotfix fixes at least 1 issue, but there are still some ones

For now, I suggest you to reboot using "reboot" then restart the server from the console.
or as said previously, switch to another image, i.e. Debian Jessie

**Comment by moul** [comment]
I'm closing this issue because it has been inactive for a few weeks.

Please reopen if you still encounter this issue.

Thank you!
