### ISSUE TITLE
locale en_US.UTF-8 isn't avaiable

### ISSUE THREAD

**Issue by favadi** [scaleway/image-debian#39]
Mosh is installed by default in debian jessie image, but doesn't work because missing locale `en_US.UTF-8`.

    The locale requested by LANG=en_US.UTF-8 isn't available here.
    Running `locale-gen en_US.UTF-8' may be necessary.
    
    The locale requested by LANG=en_US.UTF-8 isn't available here.
    Running `locale-gen en_US.UTF-8' may be necessary.
    
    mosh-server needs a UTF-8 native locale to run.
    
    Unfortunately, the local environment (LANG=en_US.UTF-8) specifies
    the character set "US-ASCII",
    
    The client-supplied environment (LANG=en_US.UTF-8) specifies
    the character set "US-ASCII".
    
    locale: Cannot set LC_CTYPE to default locale: No such file or directory
    locale: Cannot set LC_MESSAGES to default locale: No such file or directory
    locale: Cannot set LC_ALL to default locale: No such file or directory
    LANG=en_US.UTF-8
    LANGUAGE=
    LC_CTYPE="en_US.UTF-8"
    LC_NUMERIC="en_US.UTF-8"
    LC_TIME="en_US.UTF-8"
    LC_COLLATE="en_US.UTF-8"
    LC_MONETARY="en_US.UTF-8"
    LC_MESSAGES="en_US.UTF-8"
    LC_PAPER="en_US.UTF-8"
    LC_NAME="en_US.UTF-8"
    LC_ADDRESS="en_US.UTF-8"
    LC_TELEPHONE="en_US.UTF-8"
    LC_MEASUREMENT="en_US.UTF-8"
    LC_IDENTIFICATION="en_US.UTF-8"
    LC_ALL=

After SSH into the machine and run `locale-gen en_US.UTF-8`, mosh works.

Image: Debian Jessie (8.2 latest)
ID: 48a71cbc-5082-4173-a1ff-16d07e0c130f

**Comment by QuentinPerez** [comment]
Hi @favadi,

Thx for your feedback, I will investigate and fix this issue 😊

**Comment by moul** [comment]
Fixed, will be available in the next release of the Debian images

You can try to hotfix the image by looking our fix (https://github.com/QuentinPerez/image-debian/commit/4d441dbd9580284a5aa92d2f8188daa050709d68)
