### ISSUE TITLE
/etc/default permissions

### ISSUE THREAD

**Issue by mikescott** [scaleway/image-debian#55]
Hi,

I noticed today while running Jessie on one of the new VPSes, the permissions for /etc/default are wrong. On standard Debian this directory is 0755, but on Scaleway it's 0775 which causes UFW to complain when you install and enable it.

**Comment by moul** [comment]
Hi @mikescott, thank you for your feedback,

I will give a look and come back to you

**Comment by moul** [comment]
Fixed in #57, we will rebuild and release the images soon, thank you again for your feedback
