### ISSUE TITLE
Rebuild official Debian Sid image (arm)

### ISSUE THREAD

**Issue by skimpax** [scaleway/image-debian#60]
Just created a fresh new C1 with Debian Sid.
An error occurs during boot: "Failed to start SCW fetch kernel modules from Scaleway mirror".
And reboot after is very, very, very long!

When manually replaying the script, it seem depmod tool (and related) are not available (see traces below).
Error seems to come with the recent Debian Sid images (armv7l-debian-sid-2016-03-17_16:57), on which kmod is not included (while my older other C1 with Debian Sid is OK).

It may have been fixed by this very recent fix: https://github.com/scaleway/image-debian/pull/59
Unfortunately, official Debian Sid image (arm) has not been regenerated, thus not includes this fix, making it unusable.

Please rebuild the official Debian Sid image(s).

Here are traces on most recent Sid image (armv7l-debian-sid-2016-03-17_16:57) :

```console
root@scw-xxx:~#
root@scw-xxx:~# cat /etc/systemd/system/scw-sync-kernel-modules.service
[Unit]
Description=SCW fetch kernel modules from Scaleway mirror
After=NetworkManager-wait-online.service

[Service]
ExecStart=/usr/local/sbin/scw-sync-kernel-modules
Type=oneshot

[Install]
WantedBy=multi-user.target
root@scw-xxx:~#
root@scw-xxx:~#
root@scw-xxx:~# /usr/local/sbin/scw-sync-kernel-modules
/usr/local/sbin/scw-sync-kernel-modules: 38: /usr/local/sbin/scw-sync-kernel-modules: depmod: not found
root@scw-xxx:~#
root@scw-xxx:~#
root@scw-xxx:~# which lsmod
root@scw-xxx:~# which modprobe
root@scw-xxx:~# 
```

**Comment by moul** [comment]
Hi @skimpax,

As you already investigate, it is already fixed but not yet rebuild, I will rebuild and release this image by the end of the week

For now you can "hot-fix" your image by calling `apt-get install kmod`, and if you need to deploy multiple Debian Sid image with kmod pre-included, you can try to generate an image from your patched Debian Sid

**Comment by skimpax** [comment]
Installing kmod fixes the error displayed at startup about kernel modules.
Anyhow, there is still a long delay at the end of startup which leads to "Timed out waiting for dev-ttyS0.device" and "Dependency failed for Serial Getty on ttyS0" messages, and login prompt is never displayed in console (albeit I can log via SSH).
Finally, reboot command seems to be stuck, so that I have to do an electrical reboot via webGUI.

I did not have such issues with an old "Debian Sid arm" image from end of 2015 (october I think).

Hope the image to be released by end of week will fix all of this...

**Comment by moul** [comment]
Hum,

This message is usually seen when running an image with systemd (Debian Sid uses systemd) with an old kernel, can you check that you are using a recent bootscript ?

**Comment by moul** [comment]
The new image was released, you can now create new servers with kmod included

**Comment by skimpax** [comment]
Just created a new C1 server with Debian Sid (based on armv7l-debian-sid-2016-03-31_08:48 bootscript): 
 - No issue related to kernel module synchro during startup
 - But still issue with "Timed out waiting for dev-ttyS0.device" and "Dependency failed for Serial Getty on ttyS0"
 - When entering 'reboot' command, server stays stucked with following last message on console: "Reached target Shutdown." Need to do a hard reboot via webGUI to recover.

Default kernel version:
root@scw-xxx:~# uname -a
Linux scw-xxx 4.3.5-std-1 #1 SMP Fri Feb 19 11:52:18 UTC 2016 armv7l GNU/Linux
root@scw-xxx:~#

**Comment by moul** [comment]
@skimpax ok, so this is a new bug (it sometimes happen on Debian Sid/Unstable)

Can you open a new issue with the new bug so we can close the current issue and find a solution for the other bug ?

**Comment by skimpax** [comment]
OK, agree to close this one and start a fresh new issue for the fresh new image (armv7l-debian-sid-2016-03-31_08:48).
New issue created: https://github.com/scaleway/image-debian/issues/61
