### ISSUE TITLE
Running armv7hf binaries on aarch64/armv8 servers: exec format error

### ISSUE THREAD

**Issue by radfish** [scaleway/image-debian#86]
(Support has directed me to submit issue here, see ticket IHVV-8290-LWCT)

I am trying to install a chroot for armv7h on an armv8 server (Debian), but executing /bin/bash from the chroot fails with :exec format error. The aarch64 is supposed to be backward compatible with
+armv7. Why is it not working on your servers? Thank you for help.

**Comment by tbillon** [comment]
Unfortunately from what I've read, the Cavium ThunderX processor (the processor on which this offer is based) doesn't support the armhf instruction set. If you need armhf you still can use one of our C1 offer.
