### ISSUE TITLE
Add debian jessie

### ISSUE THREAD

**Issue by aimxhaisse** [scaleway/image-debian#9]

**Comment by moul** [comment]
I'm building the base image right now, we will need to use systemd init scripts now :)

https://www.debian.org/releases/jessie/armhf/release-notes/ch-whats-new.en.html#systemd

**Comment by moul** [comment]
Still need to improve systemd configuration

**Comment by aimxhaisse** [comment]
At this stage, reboot is OK, but we still have a kernel stack trace.

**Comment by aimxhaisse** [comment]
No reboot issue anymore by relying on the initrd shutdown feature, tried to reboot 16 images, did not encounter issues.
